import {
  generateKeypair,
  deriveSharedSecret,
  deriveKey,
  encryptBytes,
  decryptBytes,
  bufferToBase64url,
  base64urlToBuffer,
  exportPublicKey,
} from "./lib/crypto";

// Mocking some browser environment stuff if running in Node
import * as nodeCrypto from "crypto";
if (!globalThis.crypto) {
  globalThis.crypto = nodeCrypto.webcrypto as any;
}
if (!(globalThis as any).window) {
  (globalThis as any).window = { crypto: globalThis.crypto };
}

async function runTest() {
  console.log("=== Starting E2E Cryptographic Test ===");

  // 1. Generate keys for Device A
  console.log("1. Generating keys for Device A...");
  const deviceAKeys = await generateKeypair(true);
  const deviceAPubB64 = await exportPublicKey(deviceAKeys.publicKey);
  console.log(
    "   Device A Public Key:",
    deviceAPubB64.substring(0, 20) + "...",
  );

  // 2. Generate keys for Device B
  console.log("2. Generating keys for Device B...");
  const deviceBKeys = await generateKeypair(true);
  const deviceBPubB64 = await exportPublicKey(deviceBKeys.publicKey);
  console.log(
    "   Device B Public Key:",
    deviceBPubB64.substring(0, 20) + "...",
  );

  // --- STAGE 1: DM Encryption (Phase 9) ---
  console.log("\n--- STAGE 1: DM Encryption ---");
  const dmId = "dm_12345";
  const epoch = 1;
  const message = "Hello, this is a secret DM!";

  // Device A encrypts DM for Device B
  const sharedSecretAtoB = await deriveSharedSecret(
    deviceAKeys.privateKey,
    deviceBPubB64,
  );
  const wrapKeyAtoB = await deriveKey(
    sharedSecretAtoB,
    `dm-epoch:${epoch}`,
    dmId,
  );
  const msgBytes = new TextEncoder().encode(message);
  const ciphertextStr = await encryptBytes(wrapKeyAtoB, msgBytes.buffer);
  console.log(
    "   Device A sent ciphertext:",
    ciphertextStr.substring(0, 30) + "...",
  );

  // Device B decrypts DM from Device A
  const sharedSecretBfromA = await deriveSharedSecret(
    deviceBKeys.privateKey,
    deviceAPubB64,
  );
  const wrapKeyBfromA = await deriveKey(
    sharedSecretBfromA,
    `dm-epoch:${epoch}`,
    dmId,
  );
  const decryptedBytes = await decryptBytes(wrapKeyBfromA, ciphertextStr);
  const decryptedMsg = new TextDecoder().decode(decryptedBytes);
  console.log("   Device B decrypted message:", decryptedMsg);

  if (message !== decryptedMsg) throw new Error("DM Decryption Failed!");
  console.log("   ✅ DM Cryptographic Primitive OK");

  // --- STAGE 2: Device Linking P2P Distribution (Phase 5/8) ---
  console.log("\n--- STAGE 2: Device Linking & Channel Key Drop ---");
  // Imagine user owns Device A and is linking Device C
  const deviceCKeys = await generateKeypair(true);
  const deviceCPubB64 = await exportPublicKey(deviceCKeys.publicKey);
  const requestId = "link_req_999";

  // A channel key exists that Device A knows
  const originalChannelKey = crypto.getRandomValues(new Uint8Array(32));
  console.log("   Original Channel Key generated by Device A");

  // Device A derives shared secret with Device C proxy
  const sharedSecretAtoC = await deriveSharedSecret(
    deviceAKeys.privateKey,
    deviceCPubB64,
  );
  const linkKeyAtoC = await deriveKey(
    sharedSecretAtoC,
    requestId,
    "device-link",
  );

  // Wait, the spec says Phase 8 distribution uses "channel-key" info string
  const channelId = "chan_alpha";
  const wrapKeyForC = await deriveKey(
    sharedSecretAtoC,
    channelId,
    "channel-key",
  );

  // Encrypt the channel key for Device C
  const encryptedChannelKeyForC = await encryptBytes(
    wrapKeyForC,
    originalChannelKey.buffer,
  );
  console.log(
    "   Device A encrypted channel key for Device C:",
    encryptedChannelKeyForC.substring(0, 30) + "...",
  );

  // Device C reconstructs the channel key using its private key and Device A's public key
  const sharedSecretCfromA = await deriveSharedSecret(
    deviceCKeys.privateKey,
    deviceAPubB64,
  );
  const unwrapKeyC = await deriveKey(
    sharedSecretCfromA,
    channelId,
    "channel-key",
  );
  const reconstructedChannelKey = await decryptBytes(
    unwrapKeyC,
    encryptedChannelKeyForC,
  );

  // Verify match
  const origArray = new Uint8Array(originalChannelKey);
  const reconArray = new Uint8Array(reconstructedChannelKey);
  let match = origArray.length === reconArray.length;
  if (match) {
    for (let i = 0; i < origArray.length; i++) {
      if (origArray[i] !== reconArray[i]) match = false;
    }
  }

  if (!match) throw new Error("Channel Key reconstruction failed!");
  console.log("   ✅ P2P Channel Key Reconstruction OK");

  console.log("\n=== All Cryptographic Primitive Tests Passed ===");
}

runTest().catch(console.error);
