import uuid
from datetime import datetime

from pydantic import BaseModel
from sqlalchemy import Column, DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.core.database import Base


class DeviceLinkRequest(Base):
    """
    Holds a pending device linking request.

    Flow:
      1. New device generates a one-time ephemeral X25519 keypair (temp keypair).
      2. New device POSTs temp_public_key here, status='pending'.
      3. Old trusted device sees this request (via WebSocket or polling).
      4. Old device performs WebAuthn assertion to prove physical presence.
      5. Old device encrypts the user's private key for temp_public_key → encrypted_private_key.
      6. Status becomes 'approved'.
      7. New device decrypts encrypted_private_key using temp private key → gets user private key.
      8. New device discards temp keypair. It is now fully set up.

    temp_public_key is a throwaway keypair used only for this ceremony.
    encrypted_private_key is null until the old device writes it on approval.
    expires_at is enforced at the application layer (non-negotiable hard cutoff).
    """

    __tablename__ = "device_link_requests"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    requesting_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    new_device_id = Column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
    )

    # One-time ephemeral public key generated by the new device for this ceremony only.
    # Old device encrypts the private key for this key. Discarded after transfer.
    temp_public_key = Column(String, nullable=False)

    new_device_label = Column(String, nullable=True)  # was: device_label

    # Null until the old device approves. Filled in as base64(IV + AES-GCM ciphertext).
    encrypted_private_key = Column(String, nullable=True)

    # pending | approved | rejected | expired
    status = Column(String(20), default="pending", nullable=False)

    # Which trusted device approved this request (null until approved)
    approved_by_device_id = Column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="SET NULL"),
        nullable=True,
    )

    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=False)  # Hard cutoff — enforced in API layer

    # Relationships
    new_device = relationship(
        "Device",
        foreign_keys=[new_device_id],
        back_populates="link_requests",
    )
    approved_by_device = relationship(
        "Device",
        foreign_keys=[approved_by_device_id],
        back_populates="approved_requests",
    )


class DeviceLinkRequestResponse(BaseModel):
    request_id: str
    new_device_id: str
    new_device_label: str | None  # was: device_label
    temp_public_key: str
    webauthn_credential_id: str | None
    expires_at: str

    class Config:
        from_attributes = True
