-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.channels
(
    id uuid NOT NULL,
    server_id uuid NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    type character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    "position" integer,
    is_public boolean,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT channels_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.direct_messages
(
    id uuid NOT NULL,
    sender_id uuid NOT NULL,
    receiver_id uuid NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    edited_at timestamp without time zone,
    is_deleted boolean,
    is_read boolean,
    read_at timestamp without time zone,
    created_at timestamp without time zone,
    CONSTRAINT direct_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id uuid NOT NULL,
    channel_id uuid NOT NULL,
    user_id uuid NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    reply_to_id uuid,
    edited_at timestamp without time zone,
    is_deleted boolean,
    created_at timestamp without time zone,
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.server_members
(
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    server_id uuid NOT NULL,
    role character varying COLLATE pg_catalog."default",
    status character varying COLLATE pg_catalog."default",
    last_position_x integer,
    last_position_y integer,
    last_updated timestamp without time zone,
    joined_at timestamp without time zone,
    CONSTRAINT server_members_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.servers
(
    id uuid NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    owner_id uuid,
    map_config jsonb,
    created_at timestamp without time zone,
    access_type character varying COLLATE pg_catalog."default",
    CONSTRAINT servers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    username character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    created_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.zones
(
    id uuid NOT NULL,
    server_id uuid,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    bounds jsonb,
    CONSTRAINT zones_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.channels
    ADD CONSTRAINT channels_server_id_fkey FOREIGN KEY (server_id)
    REFERENCES public.servers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.direct_messages
    ADD CONSTRAINT direct_messages_receiver_id_fkey FOREIGN KEY (receiver_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.direct_messages
    ADD CONSTRAINT direct_messages_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_channel_id_fkey FOREIGN KEY (channel_id)
    REFERENCES public.channels (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_reply_to_id_fkey FOREIGN KEY (reply_to_id)
    REFERENCES public.messages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.server_members
    ADD CONSTRAINT server_members_server_id_fkey FOREIGN KEY (server_id)
    REFERENCES public.servers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.server_members
    ADD CONSTRAINT server_members_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.servers
    ADD CONSTRAINT servers_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zones
    ADD CONSTRAINT zones_server_id_fkey FOREIGN KEY (server_id)
    REFERENCES public.servers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;