"""Add key_backups table

Revision ID: 215e2cfe7ce1
Revises: c3e1f29a8b44
Create Date: 2026-03-10 18:41:14.099455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215e2cfe7ce1'
down_revision: Union[str, Sequence[str], None] = 'c3e1f29a8b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_backups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_blob', sa.String(), nullable=False),
    sa.Column('backup_method', sa.String(), nullable=False),
    sa.Column('prf_credential_id', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_backups')
    # ### end Alembic commands ###
