"""add_device_soft_delete

Revision ID: a283527ab996
Revises: eb5968f8a2f5
Create Date: 2026-03-10 01:09:55.513442

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a283527ab996"
down_revision: str | Sequence[str] | None = "eb5968f8a2f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "deleted_at")
    # ### end Alembic commands ###
