"""add_e2ee_schema

Revision ID: eb5968f8a2f5
Revises: f510ff35aa73
Create Date: 2026-03-09 21:28:37.562906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5968f8a2f5'
down_revision: Union[str, Sequence[str], None] = 'f510ff35aa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('webauthn_credential_id', sa.String(), nullable=True),
    sa.Column('device_label', sa.String(length=100), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_trusted_per_user', 'devices', ['user_id'], unique=False, postgresql_where='is_trusted = true')
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('dm_epochs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_dm_epoch_pair')
    )
    op.create_table('device_link_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requesting_user_id', sa.UUID(), nullable=False),
    sa.Column('new_device_id', sa.UUID(), nullable=False),
    sa.Column('temp_public_key', sa.String(), nullable=False),
    sa.Column('device_label', sa.String(length=100), nullable=True),
    sa.Column('encrypted_private_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_device_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_link_requests_requesting_user_id'), 'device_link_requests', ['requesting_user_id'], unique=False)
    op.create_table('dm_device_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dm_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('deleted_device_id', sa.UUID(), nullable=True),
    sa.Column('encrypted_ciphertext', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dm_id'], ['direct_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_device_keys_dm_id'), 'dm_device_keys', ['dm_id'], unique=False)
    op.create_index('uq_dm_device_key_active', 'dm_device_keys', ['dm_id', 'device_id'], unique=True, postgresql_where='device_id IS NOT NULL')
    op.create_table('channel_device_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('encrypted_channel_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'device_id', 'epoch', name='uq_channel_device_epoch')
    )
    op.create_index(op.f('ix_channel_device_keys_channel_id'), 'channel_device_keys', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_device_keys_device_id'), 'channel_device_keys', ['device_id'], unique=False)
    op.create_table('channel_encryption',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('epoch_rotated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.add_column('direct_messages', sa.Column('ciphertext', sa.Text(), nullable=True))
    op.add_column('direct_messages', sa.Column('epoch', sa.Integer(), nullable=True))
    op.add_column('direct_messages', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('ciphertext', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('epoch', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('is_encrypted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_encrypted')
    op.drop_column('messages', 'epoch')
    op.drop_column('messages', 'ciphertext')
    op.drop_column('direct_messages', 'is_encrypted')
    op.drop_column('direct_messages', 'epoch')
    op.drop_column('direct_messages', 'ciphertext')
    op.drop_table('channel_encryption')
    op.drop_index(op.f('ix_channel_device_keys_device_id'), table_name='channel_device_keys')
    op.drop_index(op.f('ix_channel_device_keys_channel_id'), table_name='channel_device_keys')
    op.drop_table('channel_device_keys')
    op.drop_index('uq_dm_device_key_active', table_name='dm_device_keys', postgresql_where='device_id IS NOT NULL')
    op.drop_index(op.f('ix_dm_device_keys_dm_id'), table_name='dm_device_keys')
    op.drop_table('dm_device_keys')
    op.drop_index(op.f('ix_device_link_requests_requesting_user_id'), table_name='device_link_requests')
    op.drop_table('device_link_requests')
    op.drop_table('dm_epochs')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index('ix_devices_trusted_per_user', table_name='devices', postgresql_where='is_trusted = true')
    op.drop_table('devices')
    # ### end Alembic commands ###
