"""initial schema

Revision ID: f510ff35aa73
Revises:
Create Date: 2026-03-06 20:19:35.999207

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f510ff35aa73"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
